# Generated by Django 5.1.7 on 2025-03-11 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('telegram_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('reminder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Напоминание')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('start_shift', 'Начало смены'), ('end_shift', 'Завершение смены'), ('start_break', 'Начало перерыва'), ('end_break', 'Завершение перерыва'), ('photo_received', 'Фото получено')], max_length=50, verbose_name='Операция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='botpanel.botuser')),
            ],
            options={
                'db_table': 'operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выходного')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekends', to='botpanel.botuser')),
            ],
            options={
                'db_table': 'weekends',
                'ordering': ['date'],
            },
        ),
    ]
